# -*- mode: python ; coding: utf-8 -*-

import sys
import shutil
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, copy_metadata

# --- Collect data files for key packages ----------------------------------
magika_data = collect_data_files("magika")
markitdown_data = collect_data_files("markitdown")
onnxruntime_data = collect_data_files("onnxruntime")

# --- PyInstaller onefile fix: patch gradio/component_meta.py --------------
# In one-file builds, component_meta.create_or_modify_pyi fails because
# it reads .py source files from inside the PYZ archive (which returns empty),
# causing ValueError: Couldn't find class source code.
# Strategy:
#   1. The patch file (_internal_patches/component_meta.py) has the original
#      component_meta.py source base64-embedded inside it.
#   2. At runtime, the patch exec's the original source, preserving all classes.
#   3. Only create_or_modify_pyi and get_local_contexts are overridden (no-op).
_internal_patch = Path("_internal_patches") / "component_meta.py"
_gradio_patch_src = None
_gradio_patch_backup = None
if _internal_patch.exists():
    import gradio as _gr_tmp
    _gradio_patch_src = Path(_gr_tmp.__file__).parent / "component_meta.py"
    _gradio_patch_backup = _gradio_patch_src.with_suffix(".py.bak")
    try:
        shutil.copy2(_gradio_patch_src, _gradio_patch_backup)
        shutil.copy2(_internal_patch, _gradio_patch_src)
        print(f"[MarkItDown.spec] Patched gradio/component_meta.py -> {_gradio_patch_src}")
        # Remove cached gradio modules so Analysis re-reads from disk (patched version)
        for _mod in list(sys.modules.keys()):
            if _mod == "gradio" or _mod.startswith("gradio."):
                del sys.modules[_mod]
        print(f"[MarkItDown.spec] Cleared gradio module cache")
    except (PermissionError, OSError) as _patch_err:
        _gradio_patch_src = None
        _gradio_patch_backup = None
        print(f"[MarkItDown.spec] WARNING: could not patch gradio in-place ({_patch_err})")
        print(f"[MarkItDown.spec] The runtime hook (_pyinstaller_runtime_hook.py) will handle component_meta at runtime.")
else:
    print(f"[MarkItDown.spec] WARNING: {_internal_patch} not found - gradio patch will NOT be applied!")

# -- Gradio runtime-generated modules ----------------------------------
# blocks_events.py is dynamically generated by BlocksMeta metaclass at import time.
# PyInstaller Analysis cannot discover it; we copy it explicitly as a data file.
import gradio
_gradio_src = Path(gradio.__file__).parent
_blocks_events = _gradio_src / "blocks_events.py"
if _blocks_events.exists():
    _tmp_dir = Path("dist") / "_tmp_blocks_events"
    _tmp_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(_blocks_events, _tmp_dir / "blocks_events.py")
    print(f"[MarkItDown.spec] blocks_events.py found at {_blocks_events} (size={_blocks_events.stat().st_size})")
else:
    print(f"[MarkItDown.spec] WARNING: {_blocks_events} not found - gradio codegen may not have run")

# -- Hidden imports for full markitdown feature set (NO feature dropping) --
hidden_imports = [
    # markitdown: every converter is opt-in via imports
    "markitdown",
    "markitdown.__main__",
    "markitdown._markitdown",
    "markitdown._base_converter",
    "markitdown._stream_info",
    "markitdown._uri_utils",
    "markitdown._exceptions",
    "markitdown.converters",
    "markitdown.converters._plain_text_converter",
    "markitdown.converters._html_converter",
    "markitdown.converters._markdownify",
    "markitdown.converters._rss_converter",
    "markitdown.converters._wikipedia_converter",
    "markitdown.converters._youtube_converter",
    "markitdown.converters._ipynb_converter",
    "markitdown.converters._bing_serp_converter",
    "markitdown.converters._pdf_converter",
    "markitdown.converters._docx_converter",
    "markitdown.converters._xlsx_converter",
    "markitdown.converters._pptx_converter",
    "markitdown.converters._image_converter",
    "markitdown.converters._llm_caption",
    "markitdown.converters._audio_converter",
    "markitdown.converters._transcribe_audio",
    "markitdown.converters._outlook_msg_converter",
    "markitdown.converters._zip_converter",
    "markitdown.converters._epub_converter",
    "markitdown.converters._csv_converter",
    "markitdown.converters._exiftool",
    "markitdown.converters._doc_intel_converter",
    "markitdown.converters._cu_converter",
    "markitdown.converter_utils",
    "markitdown.converter_utils.docx",
    "markitdown.converter_utils.docx.pre_process",
    "markitdown.converter_utils.docx.math",
    "markitdown.converter_utils.docx.math.omml",
    "markitdown.converter_utils.docx.math.latex_dict",
    # Magika file-type detection
    "magika",
    "magika.magika",
    "magika.types",
    "magika.types.content_type_info",
    "magika.types.content_type_label",
    "magika.types.magika_error",
    "magika.types.magika_prediction",
    "magika.types.magika_result",
    "magika.types.overwrite_reason",
    "magika.types.prediction_mode",
    "magika.types.status",
    "magika.logger",

    # Format-specific converters (kept ALL)
    "bs4",
    "markdownify",
    "requests",
    "charset_normalizer",
    "defusedxml",
    "dotenv",
    "pdfminer",
    "pdfplumber",
    "mammoth",
    "lxml",
    "pandas",
    "openpyxl",
    "xlrd",
    "pptx",
    "olefile",
    "pydub",
    "speech_recognition",
    "youtube_transcript_api",
    "onnxruntime",

    "openai",
    "httpx2",
    "httpcore2",
    "jiter",
    "truststore",
    "sniffio",

    # -- Gradio + WebUI --
    "gradio",
    "gradio.themes",
    "gradio.themes.utils",
    "gradio.themes.utils.colors",
    "gradio.themes.utils.sizes",
    "gradio.utils",
    "gradio.components",
    "gradio.routes",
    "gradio.route_utils",
    "gradio.cli",
    "gradio.data_classes",
    "gradio.context",
    "gradio.events",
    "gradio.flagging",
    "gradio.helpers",
    "gradio.layouts",
    "gradio.state_holder",
    "gradio.analytics",
    "gradio.oauth",
    "gradio.queueing",
    "gradio.templates",
    "gradio.examples",
    "gradio.blocks",
    "gradio.blocks_events",  # runtime-generated, copied above
    "gradio.component_meta",
    "fastapi",
    "starlette",
    "uvicorn",
    "uvicorn.config",
    "uvicorn.server",
    "uvicorn.lifespan",
    "uvicorn.loops",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.importer",
    "httpx",
    "safehttpx",
    "gradio_client",
    "gradio_client.client",
    "gradio_client.utils",
    "huggingface_hub",
    "huggingface_hub.utils",
    "huggingface_hub.inference",
    "multipart",
    "python_multipart",
    "pydantic",
    "pydantic.fields",
    "pydantic.main",
    "pydantic.types",
    "pydantic.json_schema",
    "pydantic_core",
    "annotated_types",
    "brotli",
    "orjson",
    "groovy",
    "ffmpy",
    "typer",
    "rich",
    "rich.console",
    "rich.markdown",
    "semantic_version",
    "tomlkit",
]

# -- Collect data from these packages -----------------------------------
datas = []
datas.extend(magika_data)
datas.extend(markitdown_data)
datas.extend(onnxruntime_data)
datas.extend(collect_data_files("gradio"))
if _blocks_events.exists():
    datas.append((str(_tmp_dir / "blocks_events.py"), "gradio"))
# Include the patched component_meta.py to override the bundled version at runtime
_patched_gradio_dir = Path("dist") / "_internal_gradio"
if _patched_gradio_dir.exists():
    datas.append((str(_patched_gradio_dir / "component_meta.py"), "gradio"))
datas.extend(collect_data_files("gradio_client"))
datas.extend(collect_data_files("huggingface_hub"))
datas.extend(collect_data_files("uvicorn"))
datas.extend(collect_data_files("fastapi"))
datas.extend(collect_data_files("starlette"))
datas.extend(collect_data_files("typer"))
datas.extend(collect_data_files("ffmpy"))
datas.extend(collect_data_files("safehttpx"))
datas.extend(collect_data_files("python_multipart"))
datas.extend(collect_data_files("annotated_types"))
datas.extend(collect_data_files("pydantic"))
datas.extend(collect_data_files("multipart"))
datas.extend(collect_data_files("groovy"))
datas.extend(collect_data_files("brotli"))
datas.extend(collect_data_files("orjson"))
datas.extend(collect_data_files("semantic_version"))
datas.extend(collect_data_files("tomlkit"))
datas.extend(collect_data_files("filelock"))
datas.extend(collect_data_files("aiofiles"))
datas.extend(collect_data_files("anyio"))
datas.extend(collect_data_files("sniffio"))
datas.extend(collect_data_files("h11"))
datas.extend(collect_data_files("websockets"))
datas.extend(collect_data_files("httpcore"))
datas.extend(collect_data_files("httpx"))
datas.extend(copy_metadata("markitdown"))
datas.extend(copy_metadata("magika"))
datas.extend(copy_metadata("gradio"))
datas.extend(copy_metadata("gradio_client"))
datas.extend(copy_metadata("huggingface_hub"))
datas.extend(copy_metadata("uvicorn"))
datas.extend(copy_metadata("fastapi"))
datas.extend(copy_metadata("starlette"))
datas.extend(copy_metadata("typer"))


# -- Excludes ----------------------------------------------------------
# Only exclude third-party packages / testing infra we know we don't need.
# Standard-library modules are intentionally NOT excluded here: removing them
# risks breaking transitive dependencies (e.g. nltk -> pydoc, defusedxml -> xml.dom).
excludes = [
    "pytest",
    "pytest_asyncio",
    "setuptools",
    "pkg_resources",
    "pip",
    "wheel",
    "easy_install",
    "tkinter",
    "turtle",
    "turtledemo",
    "idlelib",
    "antigravity",
]


block_cipher = None

a = Analysis(
    ["markitdown_gui.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=["_pyinstaller_runtime_hook.py"],
    excludes=excludes,
    noarchive=False,
    optimize=2,  # PYO bytecode optimization -> smaller frozen bytecode
)


pyz = PYZ(a.pure, cipher=block_cipher)

# -- onefile: single MarkItDown.exe (no _internal/ directory) ---------
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="MarkItDown",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        "libcrypto-3.dll",
        "libssl-3.dll",
        "python311.dll",
        "vcruntime140.dll",
        "vcruntime140_1.dll",
        "ucrtbase.dll",
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

# -- Restore original gradio/component_meta.py ------------------------
if _gradio_patch_backup and _gradio_patch_src:
    try:
        shutil.copy2(_gradio_patch_backup, _gradio_patch_src)
        _gradio_patch_backup.unlink(missing_ok=True)
        print(f"[MarkItDown.spec] Restored original gradio/component_meta.py")
    except OSError as _restore_err:
        print(f"[MarkItDown.spec] WARNING: could not restore gradio ({_restore_err})")